import unittest
from unittest.mock import patch
from uuid import uuid4

from api.routers import messages
from core import demo_store
from models.domain import IncomingMessage, TicketSource


class _AIResponse:
    status_code = 200

    @staticmethod
    def json():
        return {
            "status": "ok",
            "reply": "This answer was generated by the local AI.",
            "action": "NONE",
            "ticket_id": "ignored",
            "provider": "ollama",
        }


class _AIClient:
    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc, traceback):
        return False

    async def post(self, url, json):
        return _AIResponse()


class DemoMessageFlowTests(unittest.IsolatedAsyncioTestCase):
    async def test_database_free_flow_still_calls_ai_service(self):
        payload = IncomingMessage(
            customer_id=f"test-{uuid4()}",
            customer_name="Demo Test",
            source=TicketSource.web,
            content="How much are the Ultra Boost shoes?",
        )

        with patch.object(messages.httpx, "AsyncClient", return_value=_AIClient()):
            response = await messages._incoming_demo_fallback(payload)

        detail = demo_store.get_ticket_detail(response.data["ticket_id"])
        self.assertEqual(response.data["ai_status"], "ollama")
        self.assertEqual(detail["messages"][-1]["content"], "This answer was generated by the local AI.")

    def test_shoe_question_has_matching_deterministic_fallback(self):
        _, _, reply = demo_store.fallback_ai_reply("Giay Ultra Boost gia bao nhieu?")
        self.assertIn("Ultra Boost", reply)
        self.assertIn("1,250,000", reply)

    def test_only_resolved_conversation_can_be_deleted(self):
        ticket_id = demo_store.create_or_reuse_ticket(
            customer_id=f"delete-test-{uuid4()}",
            customer_name="Delete Test",
            source="web",
            content="Please close this test conversation.",
        )
        demo_store.add_message(ticket_id, "customer", "delete-test", "Hello")

        self.assertEqual(
            demo_store.delete_resolved_ticket(ticket_id),
            "not_resolved",
        )
        self.assertIsNotNone(demo_store.get_ticket_detail(ticket_id))

        demo_store.update_ticket(ticket_id, status="resolved")
        self.assertEqual(demo_store.delete_resolved_ticket(ticket_id), "deleted")
        self.assertIsNone(demo_store.get_ticket_detail(ticket_id))


if __name__ == "__main__":
    unittest.main()
